### ISSUE TITLE
8/9일 숙제

### ISSUE THREAD

**Issue by Feedbaek** [john-zal/GonGmG#7]
프로그래머스 레벨2
1. 타겟넘버
2. 프린트

**Comment by gongmg63** [comment]
1.https://github.com/john-zal/GonGmG/blob/main/level2/%ED%83%80%EA%B2%9F%EB%84%98%EB%B2%84.java
2.https://github.com/john-zal/GonGmG/blob/main/level2/%ED%94%84%EB%A6%B0%ED%84%B0.java

그만 괴롭혀!!!
